- name: add an apt key
  apt_key:
    url: https://packagecloud.io/fdio/release/gpgkey
- name: install source.list
  template:
    src: ubuntu/fdio.list.j2
    dest: /etc/apt/sources.list.d/fdio.list
- name: install vpp
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - vpp
- name: install vpp's optional packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - vpp-plugin-core
      - vpp-api-python
      - vpp-dbg
      - vpp-dev
      - vpp-plugin-dpdk