- name: install grafana
  become: yes
  apt:
    deb: "https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_amd64.deb"
    state: present

- name: start grafana
  become: yes
  systemd:
    name: grafana-server 
    state: restarted
    enabled: yes
    daemon_reload: yes
