- name: install grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_6.2.4_amd64.deb 
    state: present
- name: start grafana
  systemd:
    name: grafana-server 
    state: restarted
    enabled: yes
    daemon_reload: yes
