- name: install some packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - opennebula-node
- name: restart libvirt-bin
  systemd:
    name: libvirt-bin
    state: restarted
    enabled: yes
