- name: create a user for prometheus 
  become: yes
  user:
    state: present
    name: prometheus 
    system: yes
    home: /opt/prometheus
    create_home: yes

- name: download
  become: yes
  become_user: prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.10.0/prometheus-2.10.0.linux-amd64.tar.gz
    dest: /opt/prometheus/prometheus-2.10.0.linux-amd64.tar.gz
  register: tarinfo

- name: unarchive
  become: yes
  become_user: prometheus
  unarchive:
    src: "{{ tarinfo.dest }}"
    dest: /opt/prometheus
    remote_src: yes

- name: create a systemd unit file
  become: yes
  become_user: prometheus
  template:
    src: ../templates/prometheus.service
    dest: /opt/prometheus/prometheus.service

- name: create a symlink to the systemd unit file
  become: yes
  file:
    src: /opt/prometheus/prometheus.service
    dest: /etc/systemd/system/prometheus.service
    state: link

- name: generate prometheus.yml
  become: yes
  become_user: prometheus
  template:
    src: ../templates/prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: start prometheus 
  become: yes 
  systemd:
    name: prometheus 
    state: restarted
    enabled: yes
    daemon_reload: yes
