# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |c|
  c.vm.define "c1" do |c|
    c.vm.box = "centos/7"
    c.vm.provision "ansible" do |c|
      c.playbook = "playbook.yml"
    end
  end
end
