- name: Install some dependencies
  yum: name="{{ packages }}" update_cache=yes
  vars:
    packages: [ yum-utils, device-mapper-persistent-data, lvm2 ]
- name: Add a repository
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
- name: Install docker
  yum: name="{{ packages }}" update_cache=yes
  vars:
    packages: [ docker-ce, docker-ce-cli, containerd.io ]