- name: Install some dependencies
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add an apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Install source.list
  become: yes
  template:
    src: ubuntu/docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list

- name: Install docker
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: append users to docker group
  become: yes
  user:
    name: "{{ item }}"
    groups:
      - docker 
    append: yes
  loop: "{{ docker_users }}"