- name: install essential application
  become: yes
  apt: 
    name: "{{ packages }}"
    update_cache: yes
  vars: 
    packages: 
      - axel
      - curl
      - ethtool
      - ipmitool
      - git
      - gpg
      - neovim
      - tcpdump
      - tmux
      - unzip
      - zip
      - zsh